OBJS = scanner.cmx parser.cmx ast.cmx codegen.cmx philosophers_code.cmx
philosophers_code : $(OBJS)
	ocamlfind ocamlopt -linkpkg $(OBJS) -o philosophers_code
scanner.ml : scanner.mll
	ocamllex scanner.mll
parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly
%.cmo : %.ml 
	ocamlc -c $<
%.cmi : %.mli 
	ocamlc -c $<
%.cmx : %.ml
	ocamlfind ocamlopt -c $<

###Generated by "ocamldep *.ml *.mli" after building scanner.ml and parser.ml
ast.cmo : 
ast.cmx : 
codegen.cmo : ast.cmo
codegen.cmx : ast.cmx
philosophers_code.cmo : scanner.cmo parser.cmi codegen.cmo ast.cmo
philosophers_code.cmx : scanner.cmx parser.cmx codegen.cmx ast.cmx
parser.cmo : ast.cmo parser.cmi
parser.cmx : ast.cmx parser.cmi 
scanner.cmom : parser.cmi
scanner.cmx : parser.cmx
parser.cmi : ast.cmo 

###Remove all generated files
.PHONY : clean
clean: 
	ocamlbuild -clean
	rm -rf *.cmx *.cmi *.cmo *.cmx *.o tests/*.o tests/*.c tests/*.out 
	rm -rf scanner.ml parser.ml parser.mli philosophers_code


	
